services:
  - type: web
    name: boneage
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bone_age.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12